apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
data:
  eureka_service_address: http://eureka-server-0.eureka-server:8761/eureka,http://eureka-server-1.eureka-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server-0-lb
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: eureka-server-0
  ports:
    - port: 80
      targetPort: 8761
      name: eureka-server
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    app: eureka-server
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka-server
  selector:
    app: eureka-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-server
spec:
  serviceName: 'eureka-server'
  replicas: 2
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: 748487307014.dkr.ecr.eu-central-1.amazonaws.com/aws-samples-spring-cloud-microservices-event-driven/eureka-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1500m"
              memory: "256Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: aws
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: eureka_service_address
          livenessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
