server:
  port: 8091

spring:
  config:
    import: "configserver:"
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: appuser
    password: apppassword

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
