spring:
  application:
    name: customers
  config:
    import: "optional:configserver:"
  cloud:
    config:
      name: customers, common
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
