spring:
  application:
    name: customers
  config:
    import: "configserver:"
  cloud:
    config:
      name: customers, common
      discovery:
        enabled: true
        serviceId: config-server
