server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb?currentSchema=${app.db.schema}
    username: appuser
    password: apppassword

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
