server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers
          uri: lb://customers
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customers/(?<segment>.*),/$\{segment}
        - id: shipment
          uri: lb://shipment
          predicates:
            - Path=/shipment/**
          filters:
            - RewritePath=/shipment/(?<segment>.*),/$\{segment}

eureka:
  instance:
    preferIpAddress: true
