server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers
          uri: lb://customers
          predicates:
            - Path=/customers/**
          filters:
            - RewritePath=/customers/(?<segment>.*),/$\{segment}
