spring:
  application:
    name: shipment
  liquibase:
    default-schema: ${app.db.schema}
  config:
    import: "optional:configserver:"
  cloud:
    config:
      name: shipment, common
      discovery:
        enabled: true
        serviceId: config-server
    stream:
      binders:
        sns:
          type: sns
      bindings:
        customerEvents-in-0:
          binder: sns
          destination: customer-events-to-shipment-service
  jpa:
    properties:
      hibernate:
        default_schema: ${app.db.schema}

app:
  db:
    schema: shipment

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
