apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-gateway
spec:
  type: LoadBalancer
  selector:
    app: spring-cloud-gateway
  ports:
    - port: 80
      targetPort: 8080
      name: spring-cloud-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-cloud-gateway
  template:
    metadata:
      labels:
        app: spring-cloud-gateway
    spec:
      containers:
        - name: spring-cloud-gateway
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/aws-samples-spring-cloud-microservices-event-driven/spring-cloud-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "730Mi"
            limits:
              cpu: "1500m"
              memory: "730Mi"
          env:
            - name: JAVA_MEM_OPTS
              value: "-Xms256m -Xmx256m -Xss1m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:CompressedClassSpaceSize=64m -XX:+TieredCompilation -XX:+SegmentedCodeCache -XX:NonNMethodCodeHeapSize=8m -XX:ProfiledCodeHeapSize=48m -XX:NonProfiledCodeHeapSize=48m -XX:ReservedCodeCacheSize=104m"
            - name: SPRING_PROFILES_ACTIVE
              value: aws
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: eureka_service_address
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
